[gdb-snapshot]
GDB_Version: none, override, '7.6-branch'
Source0:     none, override, 'cvs://pserver:anoncvs@sourceware.org/cvs/src?module=gdb?src-prefix=src?tag=gdb_7_6-branch'
Patch0:      none, undefine, ''
Patch1:      none, undefine, ''
Patch2:      none, undefine, ''
Patch3:      none, undefine, ''
Patch4:      none, undefine, ''
Patch5:      none, undefine, ''
Patch6:      none, undefine, ''
Patch7:      none, undefine, ''
Patch8:      none, undefine, ''
Patch9:      none, undefine, ''
